name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: push
jobs:
  Dummy-Job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Yeyyy! ğŸ‰ğŸ¥³ğŸ¾ You made it!!!"
